# 字体
font_size                                    18
font_family                                  Fira Code Regular
bold_font                                    Fira Code Medium
italic_font                                  auto
bold_italic_font                             auto
symbol_map U+4E00-U+9fA5,U+9FA6-U+9FCB       LXGW WenKai Regular
