# 引用kitty基础配置文件
include kitty-basic.conf

# BEGIN_KITTY_THEME
# 引用主题配置文件Catppuccin-Mocha
include kitty-current-theme.conf
# END_KITTY_THEME

# 引用字体配置文件
include kitty-font.conf

# 引用键盘映射配置文件
include kitty-keymap.conf


